version: '3.9'

services:
  mongo:
    image: mongo:6
    container_name: test_task_mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test_task_app
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - MONGO_URL=${MONGO_URL:-mongodb://mongo:27017/test_db}
      - PORT=${PORT:-3000}
      - NODE_ENV=${NODE_ENV:-production}
    ports:
      - '${PORT:-3000}:3000'

volumes:
  mongo_data:
